version: '3.9'
services: 
  postgres:
    image: postgres
    container_name: render-postgres-finance-app
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pblnahupassword
      POSTGRES_DB: db_finance_app
      POSTGRES_HOST_AUTH_METHOD: md5
    ports:
      - "5444:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/sql/users.sql:/docker-entrypoint-initdb.d/users.sql
    networks:
      - finance-app-network
    restart: always
    healthcheck:
      test: ["CMD", "pg_isready", "-U" , "postgres", "-d", "db_finance_app"]
      interval: 5s
      retries: 5
      start_period: 10s

  # pgadmin:
  #   container_name: render-pgadmin-finance-app
  #   image: dpage/pgadmin4
  #   restart: always
  #   ports:
  #     - "8080:80"
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: pblnahu@pblnahu.com
  #     PGADMIN_DEFAULT_PASSWORD: pblnahupassword
  #   networks:
  #     - finance-app-network
  #   depends_on:
  #     - postgres
  
  server:
    build: 
      context: ./backend
      dockerfile: Dockerfile.server
    container_name: render-server-finance-app
    ports:
      - "3001:3001"
    depends_on:
      postgres: 
        condition: service_healthy
    environment:
      - DATABASE_URL=postgres://postgres:pblnahupassword@postgres:5432/db_finance_app
      - FRONTEND_URL=http://localhost:5173
      - NODE_ENV=development
    volumes:
      - ./backend:/usr/src/app
    networks:
      - finance-app-network
  
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.client
    container_name: render-client-finance-app
    ports:
      - 5173:5173
    depends_on:
      - server
    volumes:
      - ./client:/usr/src/app
    environment:
      - VITE_BACKEND_URL=http://localhost:3001
      - NODE_ENV=production
    networks:
      - finance-app-network

volumes:
  postgres_data:

networks:
  finance-app-network:
    external: true
    name: pgadmin-net
